import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar/navbar.component";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="fixed top-0 left-0 right-0 container mx-auto px-4">
          <Navbar />
        </div>
        {/* <div className="h-[100vh] w-[100vw] pt-[100px] pl-8 pr-8">{children}</div> */}
        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
